# Generated by Django 5.1.3 on 2025-09-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.ImageField(upload_to='logo')),
                ('tagline', models.TextField()),
                ('supportline', models.TextField()),
            ],
        ),
    ]
