# Generated by Django 5.1.3 on 2025-11-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
