# Generated by Django 5.1.3 on 2025-11-15 10:59

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_publicprofile_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(blank=True, null=True, upload_to=myapp.models.user_public_upload_to)),
                ('id_card', models.ImageField(blank=True, null=True, upload_to=myapp.models.user_public_upload_to)),
                ('visiting_card', models.ImageField(blank=True, null=True, upload_to=myapp.models.user_public_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='myapp.publicprofile')),
            ],
        ),
    ]
