# Generated by Django 5.1.3 on 2025-10-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
