# Generated by Django 5.1.3 on 2025-10-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_pdf_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='name',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='setup_cost',
        ),
        migrations.AddField(
            model_name='plan',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='plans'),
        ),
        migrations.AddField(
            model_name='plan',
            name='setup',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='renewal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
