# Generated by Django 5.1.3 on 2025-10-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_plan_name_remove_plan_setup_cost_plan_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
