# Generated by Django 5.1.3 on 2025-11-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_usefullink'),
    ]

    operations = [
        migrations.AddField(
            model_name='myposts',
            name='body',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
