# Generated by Django 5.1.3 on 2025-11-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSMERegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('applicant_type', models.CharField(choices=[('Proprietor', 'Proprietor'), ('Partnership', 'Partnership'), ('Pvt Ltd', 'Pvt Ltd'), ('LLP', 'LLP')], max_length=20)),
                ('business_name', models.CharField(max_length=255)),
                ('business_address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('business_type', models.CharField(choices=[('Manufacturer', 'Manufacturer'), ('Service', 'Service')], max_length=20)),
                ('date_of_starting', models.DateField()),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('bank_account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('number_of_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('investment_in_plant_machinery', models.CharField(blank=True, max_length=100, null=True)),
                ('annual_turnover', models.CharField(blank=True, max_length=100, null=True)),
                ('aadhaar_front', models.FileField(upload_to='aadhaar/')),
                ('aadhaar_back', models.FileField(upload_to='aadhaar/')),
                ('business_proof', models.FileField(upload_to='business_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
