# Generated by Django 5.1.3 on 2025-11-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_msmeregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='FssaiRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=200)),
                ('business_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('business_type', models.CharField(max_length=200)),
                ('turnover', models.CharField(max_length=50)),
                ('processing', models.CharField(max_length=200)),
                ('aadhar', models.FileField(upload_to='fssai_docs/')),
                ('photo', models.ImageField(upload_to='fssai_docs/')),
                ('shop_docs', models.FileField(upload_to='fssai_docs/')),
                ('layout', models.FileField(upload_to='fssai_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
