# Generated by Django 5.1.3 on 2025-11-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_fssairegistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trademark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('business_type', models.CharField(choices=[('Owner', 'Owner'), ('Firm', 'Firm'), ('Pvt Ltd', 'Pvt Ltd'), ('LLP', 'LLP')], max_length=20)),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_logo', models.ImageField(upload_to='trademark_docs/logos/')),
                ('classes', models.CharField(max_length=200)),
                ('business_activity', models.TextField()),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('aadhaar', models.FileField(upload_to='trademark_docs/aadhaar/')),
                ('pan', models.FileField(upload_to='trademark_docs/pan/')),
                ('business_proof', models.FileField(upload_to='trademark_docs/proof/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
