# Generated by Django 5.1.3 on 2025-12-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_trademark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalproducts',
            name='productdescription',
            field=models.TextField(max_length=1000),
        ),
    ]
