# Generated by Django 5.1.3 on 2025-12-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_digitalproducts_productdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalproducts',
            name='productname',
            field=models.CharField(max_length=50),
        ),
    ]
