# Generated by Django 5.1.3 on 2025-11-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_category_alter_digitalproducts_productdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('main', 'Main User'), ('crm', 'CRM User'), ('vendor', 'Vendor'), ('admin', 'Admin Panel')], default='main', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payout_upi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
