# Generated by Django 5.1.3 on 2025-11-09 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_profile_role_alter_profile_payout_upi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_reseller',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='kyc_submitted',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='payout_upi',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='service',
            field=models.CharField(blank=True, choices=[('Fintech', 'Indokona Fintech'), ('Suit', 'Indokona Suite'), ('SaaS', 'Indokona SaaS'), ('M2M', 'Indokona M2M'), ('Store', 'Indokona Digital Store'), ('Acadmy', 'Indokona Academy')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Retailer', 'Retailer'), ('Distributor', 'Distributor'), ('Master Distributor', 'Master Distributor'), ('Super Distributor', 'Super Distributor'), ('White Label', 'White Label'), ('Basic Reseller', 'Basic Reseller'), ('Pro Reseller', 'Pro Reseller'), ('Gold Reseller', 'Gold Reseller'), ('Diamond Reseller', 'Diamond Reseller')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
