# Generated by Django 5.1.3 on 2025-11-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_profile_is_reseller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Retailer', 'Retailer'), ('Distributor', 'Distributor'), ('Master Distributor', 'Master Distributor'), ('Super Distributor', 'Super Distributor'), ('White Label', 'White Label'), ('Basic Reseller', 'Basic Reseller'), ('Pro Reseller', 'Pro Reseller'), ('Gold Reseller', 'Gold Reseller'), ('Diamond Reseller', 'Diamond Reseller')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='service',
            field=models.CharField(blank=True, choices=[('Fintech', 'Indokona Fintech'), ('Suit', 'Indokona Suite'), ('SaaS', 'Indokona SaaS'), ('M2M', 'Indokona M2M'), ('Store', 'Indokona Digital Store'), ('Acadmy', 'Indokona Academy')], max_length=50, null=True),
        ),
    ]
