# Generated by Django 5.1.3 on 2025-11-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_profile_role_alter_profile_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField()),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='music')),
                ('likes', models.IntegerField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MyReels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField()),
                ('caption', models.CharField(max_length=50)),
                ('src', models.FileField(upload_to='reels')),
                ('music', models.FileField(upload_to='music')),
            ],
        ),
        migrations.CreateModel(
            name='PublicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('userpic', models.ImageField(upload_to='public/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pincode', models.IntegerField()),
                ('is_varied', models.BooleanField(default=False)),
                ('aadhar_number', models.CharField(max_length=20, unique=True)),
                ('aadhar_card_pic', models.FileField(upload_to='aadhar/')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Retailer', 'Retailer'), ('Distributor', 'Distributor'), ('Master Distributor', 'Master Distributor'), ('Super Distributor', 'Super Distributor'), ('White Label', 'White Label'), ('Basic Reseller', 'Basic Reseller'), ('Pro Reseller', 'Pro Reseller'), ('Gold Reseller', 'Gold Reseller'), ('Diamond Reseller', 'Diamond Reseller')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='service',
            field=models.CharField(blank=True, choices=[('Fintech', 'Indokona Fintech'), ('Suit', 'Indokona Suite'), ('SaaS', 'Indokona SaaS'), ('M2M', 'Indokona M2M'), ('Store', 'Indokona Digital Store'), ('Acadmy', 'Indokona Academy')], default=None, max_length=50, null=True),
        ),
    ]
