# Generated by Django 5.1.3 on 2025-11-13 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_myreels_likes_alter_myreels_music_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myreels',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
